source('~/DataScienceCoursera/RProgramming/20151025_week3/ProgrammingAssignment2/cachematrix.R')
x = matrix(1:4, 2, 2)
solve(x)
ix = solve(x)
ix %*% x
c_x = makeCacheMatrix(x)
cacheSolve(c_x)
cacheSolve(c_x)
c_x$getinv()
inv = solve(x)
c_x = makeCacheMatrix(x)
cacheSolve(c_x)
cacheSolve(c_x)
inv
x = matrix(2:5, 2, 2)
c_x = makeCacheMatrix(x)
inv
cacheSolve(c_x)
inv
source("cachevector.R")
v = c(1:5)
c_v = makeVector(v)
cachemean(c_v)
cachemean(c_v)
c_x = makeCacheMatrix(x)
cacheSolve(c_x)
cacheSolve(c_x)
source("cachematrix.R")
c_x = makeCacheMatrix(x)
cacheSolve(c_x)
cacheSolve(c_x)
savehistory("~/DataScienceCoursera/RProgramming/20151025_week3/ProgrammingAssignment2/test_script.R")
